### PR TITLE
Modernize & fix #422

### LINKED ISSUE #422: Delete the name of collections in error messages
When errors are returned (If the input information is incorrect) , The name of the corresponding collection is also in the error message . LIKE this :

name is required in CollectionName insert

i want this part (in CollectionName insert ) gone.

error messages belong to software users, and users do not need to see the name of the collection.
And this part should not be returned at all.

And this is about this line:

[https://github.com/Meteor-Community-Packages/meteor-collection2/blob/master/package/collection2/collection2.js#L479](https://github.com/Meteor-Community-Packages/meteor-collection2/blob/master/package/collection2/collection2.js#L479)

I also raised this issue in the simpl-schema, but it is not related to simpl-schema.

For more details, please refer to the following links:

[https://github.com/aldeed/simpl-schema/issues/408](https://github.com/aldeed/simpl-schema/issues/408)

[https://forums.meteor.com/t/delete-the-name-of-collections-in-error-messages-in-simpl-schema/54073/18](https://forums.meteor.com/t/delete-the-name-of-collections-in-error-messages-in-simpl-schema/54073/18)

### PR DESCRIPTION
**Pull request by StorytellerCZ**
**Table of Contents**  *generated with [DocToc](https://github.com/thlorenz/doctoc)*

- [What](#what)
- [Why](#why)

## What
* Modernize code
* Remove unused dependency `clone`
* Fix #422 
* Fix LGTM errors

## Why
As far as I and my IDE has seen `clone` is no longer used, please correct me if I'm missing something here.

Then I have updated `var` to `let` and `const` and one loop for `forEach` loop.

Finally this PR also includes a proposed solution for #422.

### CODE REVIEW

**Comment by harryadel** [comment]
You seem to be still making modifications. :sweat_smile: Please let me know when you're done.

**Comment by StorytellerCZ** [comment]
@harryadel sorry, noticed the LGTM errors so I went ahead and fixed them. There was actually one bug in that.

File: package/collection2/collection2.js [hunk 1]
```diff
@@ -476,7 +474,7 @@ function doValidate(collection, type, args, getAutoValues, userId, isFromTrusted
 
     return args;
   } else {
-    error = getErrorObject(validationContext, `in ${collection._name} ${type}`);
+    error = getErrorObject(validationContext, Meteor.isProduction ? '' : `in ${collection._name} ${type}`);
```
Comment (harryadel) [inline package/collection2/collection2.js:477]: I understand that you made this change for https://github.com/Meteor-Community-Packages/meteor-collection2/issues/422 but if we're going to implement this it's better to let users decided for themselves instead of forcefully adding with no way to change it.

Comment (harryadel) [reply package/collection2/collection2.js:477]: How about adding `disableCollectionNamesInProduction` property to collection2 and having it on by default?

**Review by harryadel — CHANGES_REQUESTED** [review]

File: package/collection2/package.js [hunk 2]
```diff
@@ -18,7 +17,7 @@ Npm.depends({
 Package.onUse(function(api) {
```
Comment (copleykj) [inline package/collection2/package.js:17]: Could we use `api.versionsFrom` here, instead of specific versions of core packages?

Comment (StorytellerCZ) [reply package/collection2/package.js:17]: Done, set it to `1.12.1` for now. We can discuss if we want to go lower.

File: package/collection2/collection2.js (hunk 1 above)
Comment (StorytellerCZ) [reply package/collection2/collection2.js:477]: Will do, but we will set this on for the next major release.

**Review by copleykj — APPROVED** [review]

**Review by harryadel — APPROVED** [review]
